name: Run Greeting

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello ${{ inputs.name }}"
  goodbye:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Goodbye ${{ inputs.name }}"
