name: ci

on:
  push:

env:
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/test:test
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/test:latest

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: CACHE_BUSTER="${{ github.sha }}"
          cache-from: type=registry,ref=$TEST_TAG
          cache-to: inline
          tags: |
            ${{ env.TEST_TAG }}
            ${{ env.LATEST_TAG }}
      -
        id: tag
        run: echo "tag=${{ env.TEST_TAG }}" >> "$GITHUB_OUTPUT"
  test:
    needs: build
    runs-on: ubuntu-latest
    environment: test
    container:
      image: ${{ needs.build.outputs.tag }}
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      -
        name: Test step
        run: |
          curl -V

